=== ChetWang/qilworkstudy/trunk/InMemDB_develop/codes/InMemDBEE/src/resources/tables.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="tables">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="table" maxOccurs="unbounded" minOccurs="0">

					<xs:complexType>

						<xs:sequence>
							<xs:element name="column" maxOccurs="unbounded"
								minOccurs="1">
								<xs:complexType>
									<xs:attribute name="name" use="required">
										<xs:simpleType>
											<xs:restriction base="xs:string">
												<xs:pattern value="[A-Z]+[0-9A-Z]*" />
											</xs:restriction>
										</xs:simpleType>
									</xs:attribute>
									<xs:attribute name="type" use="required">
										<xs:simpleType>
											<xs:restriction base="xs:string">
												<xs:enumeration value="int"></xs:enumeration>
												<xs:enumeration value="long"></xs:enumeration>
												<xs:enumeration value="double"></xs:enumeration>
												<xs:enumeration value="varchar"></xs:enumeration>
												<xs:enumeration value="number"></xs:enumeration>
												<xs:enumeration value="date"></xs:enumeration>
												<xs:enumeration value="time"></xs:enumeration>
												<xs:enumeration value="bool"></xs:enumeration>
											</xs:restriction>
										</xs:simpleType>
									</xs:attribute>
									<xs:attribute name="autoIncrement" use="optional">
										<xs:simpleType>
											<xs:restriction base="xs:string">
												<xs:enumeration value="true"></xs:enumeration>
												<xs:enumeration value="false"></xs:enumeration>
											</xs:restriction>
										</xs:simpleType>
									</xs:attribute>
									<xs:attribute name="length" use="required">
										<xs:simpleType>
											<xs:restriction base="xs:string">
												<xs:pattern value="[0-9]*" />
											</xs:restriction>
										</xs:simpleType>
									</xs:attribute>
									<xs:attribute name="primarykey" use="required">
										<xs:simpleType>
											<xs:restriction base="xs:string">
												<xs:enumeration value="true"></xs:enumeration>
												<xs:enumeration value="false"></xs:enumeration>
											</xs:restriction>
										</xs:simpleType>
									</xs:attribute>
									<xs:attribute name="index" use="required">
										<xs:simpleType>
											<xs:restriction base="xs:string">
												<xs:enumeration value="true"></xs:enumeration>
												<xs:enumeration value="false"></xs:enumeration>
											</xs:restriction>
										</xs:simpleType>
									</xs:attribute>
								</xs:complexType>
								<xs:unique name="columnUnique">
									<xs:selector xpath="./tables/table/column"></xs:selector>
									<xs:field xpath="@name"></xs:field>
								</xs:unique>
							</xs:element>

						</xs:sequence>

						<xs:attribute name="name" use="required">
							<xs:simpleType>
								<xs:restriction base="xs:string">
									<xs:pattern value="[A-Z]+[0-9A-Z]*" />
								</xs:restriction>

							</xs:simpleType>
						</xs:attribute>
						<xs:attribute name="maxRowCount" use="optional">
							<xs:simpleType>
								<xs:restriction base="xs:string">
									<xs:pattern value="[0-9]+" />
								</xs:restriction>

							</xs:simpleType>
						</xs:attribute>
					</xs:complexType>
					<xs:unique name="tableUnique">
						<xs:selector xpath="./tables/table"></xs:selector>
						<xs:field xpath="@name"></xs:field>
					</xs:unique>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

</xs:schema>

=== ChetWang/qilworkstudy/trunk/InMemDB_develop/codes/InMemDBEE/src/resources/tables.xml
<?xml version="1.0" encoding="UTF-8"?>
<tables xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="tables.xsd">
	<!-- 注意！！！！！所有表名、列名必须大写！！！！！！ maxRowCount="0"表示不做行数限制 -->
	<table name="TTTT" maxRowCount="400000">
		<column name="II" type="int" length="" primarykey="true" index="false" />
		<column name="AA" type="varchar" length="100" primarykey="true"
			index="false" />
		<column name="BB" type="varchar" length="400" primarykey="false"
			index="false" />
	</table>
	<table name="PPPP" maxRowCount="0">
		<column name="II" type="int" length="" primarykey="true" index="false" />
		<column name="AA" type="varchar" length="100" primarykey="false"
			index="false" />
		<column name="BB" type="varchar" length="400" primarykey="false"
			index="false" />
	</table>
	<table name="AAAA" maxRowCount="4000">
		<column name="II" type="int" length="" primarykey="true" index="false" />
		<column name="AA" type="varchar" length="100" primarykey="false"
			index="false" />
		<column name="BB" type="varchar" length="400" primarykey="false"
			index="false" />
	</table>
	<table name="FFFF" maxRowCount="20000">
		<column name="II" type="int" length="" primarykey="true" index="false" />
		<column name="AA" type="varchar" length="100" primarykey="false"
			index="false" />
		<column name="BB" type="varchar" length="400" primarykey="false"
			index="false" />
	</table>

</tables>
