=== ChetWang/qilworkstudy/trunk/ReleaseAutomationPython/scripts/dist/applist.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT Baseline (ComponentName,ComponentEmail,Description,EnterpriseApps) >
<!ELEMENT ComponentName (#PCDATA)>
<!ELEMENT ComponentEmail (#PCDATA)>
<!ELEMENT Description (#PCDATA)>

<!ELEMENT EnterpriseApps (EnterpriseApp*)>
<!ELEMENT EnterpriseApp (earfiles,clusters?,nodes?,urls,responses)>
<!ATTLIST EnterpriseApp name CDATA #REQUIRED>

<!ELEMENT earfiles (#PCDATA)>

<!ELEMENT clusters (cluster*)>
<!ELEMENT cluster (#PCDATA)>
<!ATTLIST cluster name CDATA #REQUIRED>

<!ELEMENT nodes (node*)>
<!ELEMENT node (servers)>
<!ATTLIST node name CDATA #REQUIRED>

<!ELEMENT servers (server*)>
<!ELEMENT server (#PCDATA)>
<!ATTLIST server name CDATA #REQUIRED>


<!ELEMENT urls (url*)>
<!ELEMENT url (#PCDATA)>

<!ELEMENT responses (response*)>
<!ELEMENT response (#PCDATA)>

=== ChetWang/qilworkstudy/ReleaseAutomationPython/scripts/backup/ReleaseAutomation2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Baseline SYSTEM "applist.dtd">
<Baseline>
    <ComponentName>TA</ComponentName>
    <ComponentEmail>espear.ta@db.com</ComponentEmail>
    <Description>Release Automation Test Application</Description>
    <EnterpriseApps>
        <EnterpriseApp name="Release Automation Test App">
            <earfiles>ReleaseAutomation.ear</earfiles>
            <clusters>
                <cluster name="TradesCluster"/>
            </clusters>
            
            <urls>
                <url>http://localhost/ReleaseAutomationWeb/index.html</url>
            </urls>
            <responses>
                <response>ReleaseAutomation Test Page</response>
            </responses>
        </EnterpriseApp>
    </EnterpriseApps>
</Baseline>

=== ChetWang/qilworkstudy/trunk/ReleaseAutomationPython/scripts/backup/win.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Baseline SYSTEM "applist.dtd">
<Baseline>
    <ComponentName>eSpear TA</ComponentName>
    <ComponentEmail>frank.zhu@sssltd.cn</ComponentEmail>
    <Description>ta</Description>
    <EnterpriseApps>
        <EnterpriseApp name="RA">
            <earfiles>C:/IBM/WebSphere/scripts/eardist/ReleaseAutomation.ear</earfiles>
            <nodes>
                <node name="EUSNode">
					<servers>
                        <server name="Testserver"/>
                    </servers>
                </node>
            </nodes>
            <urls>
                <url>http://cy5468lap/ReleaseAutomationWeb/index.html</url>
            </urls>
            <!--<responses>
                <response>ReleaseAutomation Test Page</response>
            </responses>
        --></EnterpriseApp>
    </EnterpriseApps>
</Baseline>

=== ChetWang/qilworkstudy/ReleaseAutomationPython/scripts/backup/ReleaseAutomation.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Baseline SYSTEM "applist.dtd">
<Baseline>
    <ComponentName>TA</ComponentName>
    <ComponentEmail>espear.ta@db.com</ComponentEmail>
    <Description>Release Automation Test Application</Description>
    <EnterpriseApps>
        <EnterpriseApp name="ReleaseAutomationTestApp">
            <earfiles>ReleaseAutomation.ear</earfiles>
            <nodes>
                <node name="eSpearNode">
                    <servers>
                        <server name="EMMS"/>
                    </servers>
                </node>
            </nodes>
            <urls>
                <url>http://localhost/ReleaseAutomationWeb/index.html</url>
            </urls>
            <responses>
                <response>ReleaseAutomation Test Page</response>
            </responses>
        </EnterpriseApp>
    </EnterpriseApps>
</Baseline>
